# Generated by Django 5.2.12 on 2026-03-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0003_pollresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollUser',
        ),
    ]
