# Generated by Django 5.2.12 on 2026-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0007_school_opinion_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('school_opinion', 'School Opinion'), ('teacher_feedback', 'Teacher Feedback'), ('student_life', 'Student Life')], max_length=50)),
            ],
        ),
    ]
