# Generated by Django 5.2.12 on 2026-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0008_pollquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='category',
            field=models.CharField(choices=[('school_opinion', 'School Opinion'), ('event', 'event'), ('academic_subject', 'academic_subject')], max_length=50),
        ),
    ]
