# Generated by Django 5.2.12 on 2026-03-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0009_alter_pollquestion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='option3',
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pollapp.pollquestion')),
            ],
        ),
    ]
